### ISSUE TITLE
Configurable hotkeys

### ISSUE THREAD

**Issue by ArielHorwitz** [ArielHorwitz/hummingparrot#7]
Hotkeys are hardcoded and not documented anywhere. They should be configurable in `config.toml`.

**Comment by FriedlandAaron** [comment]
Started working on this in a new branch. Really messy and dirty, will clean it up a bit later.
The general idea is:
- create a hashmap to map hotkeys to the actions they perform
- replace all hardcoded instances of checking key combinations to refer to the mapping result instead

This will allow us to make it configurable later using the config file

**Comment by ArielHorwitz** [comment]
Awesome!

Also, now that I see collaboration I'll make sure to PR before merging in main :)

**Comment by ArielHorwitz** [comment]
The solution is great, imo.

A suggestion that may make it less messy: add a "scope" to the code+modifiers that determines when the hotkey is active. E.g. a "global" scope is always active, while "conversation" and "config" scopes are only active in the respective tabs. I call it scope because that's what I've seen it called in other programs.

**Comment by FriedlandAaron** [comment]
> A suggestion that may make it less messy: add a "scope" to the code+modifiers that determines when the hotkey is active. E.g. a "global" scope is always active, while "conversation" and "config" scopes are only active in the respective tabs. I call it scope because that's what I've seen it called in other programs.

This was something I was having thoughts about, wasn't sure yet about the implementation. At first I was thinking maybe adding a layer of indirection in the Hashmap itself, first mapping to "scope" and then to the hotkeys, then I thought about holding separate maps for separate "scopes". I guess a simpler solution would be to just add it to the tuple, which would also theoretically allow the same hotkey to be used for different purposes in different "scopes".

**Comment by ArielHorwitz** [comment]
Yeah I think just having a `Hotkey` struct with scope, key, and modifier would be good. Also, using the same hotkey in different scopes should be desirable (most obvious being Enter or arrow keys). This may also mean that it's worth considering subdividing the `HotkeyAction` enum by scope...

**Comment by FriedlandAaron** [comment]
Actually, I don't think the `HotkeyAction` enum would need to be subdivided in that case. That's the beauty of that abstraction layer, the action can be independent of the hotkey, and the mapping will hold whatever hotkeys and scopes do whichever actions.
